@baseUrl = http://localhost
@port = 8000
@host = {{baseUrl}}:{{port}}
@contentType = application/json

### Check api status
# @name checkApiStatus
GET {{host}}/
Accept: application/json

### Gel all students
# @name getAllStudents
GET {{host}}/students

### Get student by id
@studentIdDynamic = {{getAllStudents.response.body.$[0].ID}}

GET {{host}}/students/{{studentIdDynamic}}

### Post new contact
# @prompt contactName
POST {{host}}/students
Content-Type: {{contentType}}

{
    "name": "{{contactName}}",
    "document": "{{$randomInt 1111111111 9999999999}}",
    "email": "{{contactName}}@test.com"
}

### Edit new contact
# @prompt contactName
PUT {{host}}/students/{{studentId}}
Content-Type: {{contentType}}

{
    "name": "{{contactName}}",
    "phone": "{{$randomInt 1111111111 9999999999}}",
    "email": "{{contactName}}@test.com"
}

### Get category by slug
DELETE {{host}}/students/{{studentId}}