@baseUrl = http://localhost
@port = 8000
@host = {{baseUrl}}:{{port}}
@contentType = application/json

### Check api status
# @name checkApiStatus
GET {{host}}/
Accept: application/json

### Gel all students
# @name getAllStudents
GET {{host}}/students

### Get student by id
@studentIdDynamic = {{getAllStudents.response.body.$[0].ID}}

GET {{host}}/students/{{studentIdDynamic}}

### Post new contact
# @prompt studentName
POST {{host}}/students
Content-Type: {{contentType}}

{
    "name": "{{studentName}}",
    "phone": "{{$randomInt 1111111111 9999999999}}",
    "document": "{{$randomInt 1111111111 9999999999}}",
    "email": "{{studentName}}@test.com"
}

### Edit student
# @prompt studentId
# @prompt studentName
PUT {{host}}/students/{{studentId}}
Content-Type: {{contentType}}

{
    "name": "{{studentName}}",
    "phone": "{{$randomInt 1111111111 9999999999}}",
    "document": "{{$randomInt 1111111111 9999999999}}",
    "email": "{{studentName}}@test.com"
}

### Delete student
# @prompt studentId
DELETE {{host}}/students/{{studentId}}

### Find student by document
# @prompt studentDocument
GET {{host}}/students/document?document={{studentDocument}}
